"use client";

import { useEffect, useMemo, useState } from "react";

type Post={id:string;beauty_code:string;category:string;title:string;content:string;product_url:string|null;image_url:string|null;like_count:number;comment_count:number;status:string;created_at:string};
type Comment={id:string;post_id:string;beauty_code:string;content:string;status:string;created_at:string};
type Report={id:string;post_id:string;reason:string;created_at:string};
type Data={ok:boolean;posts:Post[];comments:Comment[];reports:Report[]};

export default function AdminCommunityPage(){
  const [data,setData]=useState<Data|null>(null); const [tab,setTab]=useState<"posts"|"comments"|"reports">("posts"); const [q,setQ]=useState(""); const [busy,setBusy]=useState("");
  async function load(){const r=await fetch("/api/admin/community",{cache:"no-store"});setData(await r.json());}
  useEffect(()=>{load();},[]);
  async function remove(type:"post"|"comment",id:string,label:string){if(!confirm(`${label}을 삭제하시겠습니까? 사용자 화면에서 즉시 숨겨집니다.`))return;setBusy(id);const r=await fetch("/api/admin/community",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,id})});const p=await r.json();setBusy("");if(!p.ok){alert(p.message??"삭제 실패");return;}await load();}
  const posts=useMemo(()=>data?.posts.filter(x=>!q||`${x.beauty_code} ${x.category} ${x.title} ${x.content}`.toLowerCase().includes(q.toLowerCase()))??[],[data,q]);
  const comments=useMemo(()=>data?.comments.filter(x=>!q||`${x.beauty_code} ${x.content}`.toLowerCase().includes(q.toLowerCase()))??[],[data,q]);
  const reports=data?.reports??[]; const visiblePosts=data?.posts.filter(x=>x.status==="visible").length??0; const visibleComments=data?.comments.filter(x=>x.status==="visible").length??0;
  return <main className="min-h-screen bg-[#fbf7f7] p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header><p className="text-xs font-semibold tracking-[.16em] text-[#a94f65]">COMMUNITY MODERATION</p><h1 className="mt-2 text-3xl font-semibold">커뮤니티 관리</h1><p className="mt-2 text-sm text-[#74676a]">게시글·댓글·신고 내역을 확인하고 관리자가 부적절한 콘텐츠를 즉시 삭제할 수 있습니다.</p></header>
    <section className="grid gap-4 sm:grid-cols-3"><Card k="노출 게시글" v={visiblePosts}/><Card k="노출 댓글" v={visibleComments}/><Card k="누적 신고" v={reports.length}/></section>
    <section className="rounded-2xl border border-[#eadfe1] bg-white p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex gap-2">{[["posts","게시글"],["comments","댓글"],["reports","신고"]].map(([k,l])=><button key={k} onClick={()=>setTab(k as any)} className={`rounded-full px-4 py-2 text-sm font-semibold ${tab===k?"bg-[#a94f65] text-white":"bg-[#f5ecee] text-[#65585b]"}`}>{l}</button>)}</div>{tab!=="reports"&&<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Beauty Code·제목·내용 검색" className="w-full rounded-xl border border-[#dfd3d6] px-4 py-2.5 text-sm md:w-80"/>}</div>
    {tab==="posts"&&<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead><tr className="border-b text-xs text-[#988b8e]"><th className="p-3">Code</th><th className="p-3">카테고리</th><th className="p-3">제목/내용</th><th className="p-3">좋아요</th><th className="p-3">댓글</th><th className="p-3">상태</th><th className="p-3">등록일</th><th className="p-3"></th></tr></thead><tbody>{posts.map(x=><tr key={x.id} className="border-b border-[#f1e8ea] align-top"><td className="p-3 font-semibold">{x.beauty_code}</td><td className="p-3">{x.category}</td><td className="p-3"><p className="font-semibold">{x.title}</p><p className="mt-1 max-w-xl whitespace-pre-wrap text-xs leading-5 text-[#74676a]">{x.content}</p>{x.product_url&&<a href={x.product_url} target="_blank" className="mt-1 block text-xs text-[#a94f65] underline">상품 링크</a>}</td><td className="p-3">{x.like_count}</td><td className="p-3">{x.comment_count}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${x.status==="visible"?"bg-emerald-50 text-emerald-700":"bg-gray-100 text-gray-500"}`}>{x.status==="visible"?"노출":"삭제됨"}</span></td><td className="p-3 text-xs">{new Date(x.created_at).toLocaleString("ko-KR")}</td><td className="p-3">{x.status==="visible"&&<button disabled={busy===x.id} onClick={()=>remove("post",x.id,"게시글")} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-600 disabled:opacity-40">삭제</button>}</td></tr>)}</tbody></table></div>}
    {tab==="comments"&&<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr className="border-b text-xs text-[#988b8e]"><th className="p-3">Code</th><th className="p-3">댓글</th><th className="p-3">상태</th><th className="p-3">등록일</th><th className="p-3"></th></tr></thead><tbody>{comments.map(x=><tr key={x.id} className="border-b border-[#f1e8ea]"><td className="p-3 font-semibold">{x.beauty_code}</td><td className="p-3">{x.content}</td><td className="p-3">{x.status==="visible"?"노출":"삭제됨"}</td><td className="p-3 text-xs">{new Date(x.created_at).toLocaleString("ko-KR")}</td><td className="p-3">{x.status==="visible"&&<button disabled={busy===x.id} onClick={()=>remove("comment",x.id,"댓글")} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-600 disabled:opacity-40">삭제</button>}</td></tr>)}</tbody></table></div>}
    {tab==="reports"&&<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-xs text-[#988b8e]"><th className="p-3">게시글 ID</th><th className="p-3">신고 사유</th><th className="p-3">신고일</th></tr></thead><tbody>{reports.map(x=><tr key={x.id} className="border-b border-[#f1e8ea]"><td className="p-3 font-mono text-xs">{x.post_id}</td><td className="p-3">{x.reason}</td><td className="p-3 text-xs">{new Date(x.created_at).toLocaleString("ko-KR")}</td></tr>)}</tbody></table></div>}
    </section>
  </div></main>;
}
function Card({k,v}:{k:string;v:number}){return <div className="rounded-2xl border border-[#eadfe1] bg-white p-5"><p className="text-xs font-semibold text-[#9b8d90]">{k}</p><p className="mt-2 text-2xl font-semibold">{v}</p></div>}
