"use client";

import { useEffect, useState } from "react";
import { useLanguage } from "./i18n";

const ANSWERS_KEY="layad-test-answers";
const SESSION_KEY="layad-supabase-session-id";
const SAVED_CODE_KEY="layad-saved-beauty-code";
const SAVED_SOURCE_KEY="layad-saved-beauty-code-source";
const SAVING_KEY="layad-supabase-session-saving";
type AnswerMap=Record<number,string>;
type BeautyCodeSource="test";
type AgeBand="14-19"|"20-29"|"30-39"|"40-49"|"50-59"|"60+"|"prefer_not_to_say";
const ageValues:AgeBand[]=["14-19","20-29","30-39","40-49","50-59","60+","prefer_not_to_say"];
const copy={
 ko:{ageTitle:"연령대를 선택해 주세요",ageDesc:"서비스 개선을 위한 선택 항목입니다. 정확한 나이와 생년월일은 저장하지 않습니다.",skip:"선택하지 않고 저장",close:"안내 닫기",chooseCode:"Beauty Code를 먼저 선택해 주세요.",pending:"현재 저장 준비 중입니다. 결과는 이 기기에 임시 보관되었습니다.",fail:"저장에 실패했습니다. 결과 화면은 계속 이용할 수 있습니다.",saved:"익명 테스트 데이터가 저장되었습니다.",network:"네트워크 문제로 이 기기에 임시 보관했습니다.",ages:{"14-19":"14–19세","20-29":"20–29세","30-39":"30–39세","40-49":"40–49세","50-59":"50–59세","60+":"60세 이상",prefer_not_to_say:"응답하지 않음"}},
 en:{ageTitle:"Select your age range",ageDesc:"This optional item helps improve the service. We do not store your exact age or date of birth.",skip:"Save without selecting",close:"Close notice",chooseCode:"Please choose a Beauty Code first.",pending:"Saving is temporarily unavailable. Your result is stored on this device.",fail:"Could not save. You can continue using the result screen.",saved:"Anonymous test data saved.",network:"A network issue occurred. Your data is temporarily stored on this device.",ages:{"14-19":"14–19","20-29":"20–29","30-39":"30–39","40-49":"40–49","50-59":"50–59","60+":"60+",prefer_not_to_say:"Prefer not to say"}},
 ja:{ageTitle:"年齢層を選択してください",ageDesc:"サービス改善のための任意項目です。正確な年齢や生年月日は保存しません。",skip:"選択せずに保存",close:"お知らせを閉じる",chooseCode:"Beauty Codeを先に選択してください。",pending:"現在保存準備中です。結果はこの端末に一時保存されました。",fail:"保存できませんでした。結果画面は引き続き利用できます。",saved:"匿名テストデータを保存しました。",network:"ネットワークの問題により、この端末に一時保存しました。",ages:{"14-19":"14–19歳","20-29":"20–29歳","30-39":"30–39歳","40-49":"40–49歳","50-59":"50–59歳","60+":"60歳以上",prefer_not_to_say:"回答しない"}},
} as const;
const ANALYSIS_LABELS=["적합도 분석하기","잘 맞는지 확인하기","Analyze fit","Analyze product fit","Check product fit","適合度を分析","相性を確認"];
const RETEST_LABELS=["테스트 다시 하기","Retake test","Take the test again","テストをやり直す","もう一度テスト"];
function readAnswers():AnswerMap{try{return JSON.parse(sessionStorage.getItem(ANSWERS_KEY)??"{}") as AnswerMap;}catch{return {};}}
function findBeautyCode(){return Array.from(document.querySelectorAll("h1, p")).map(e=>e.textContent?.trim()??"").find(text=>/^[OD][GM][PC][VE]$/.test(text));}
function findCurrentQuestionId(){const label=Array.from(document.querySelectorAll("p")).find(e=>e.textContent?.trim().startsWith("QUESTION "));const match=label?.textContent?.match(/QUESTION\s+(\d{1,2})/);return match?Number(match[1]):null;}
function findAnswerCode(button:HTMLButtonElement){return Array.from(button.querySelectorAll("span")).map(e=>e.textContent?.trim()??"").find(text=>/^[ODGMPCVE]$/.test(text))??null;}

export default function AnonymousDataCapture(){
 const {locale}=useLanguage(); const t=copy[locale];
 const [source,setSource]=useState<BeautyCodeSource|null>(null); const [beautyCode,setBeautyCode]=useState<string|null>(null); const [showAgePrompt,setShowAgePrompt]=useState(false); const [saving,setSaving]=useState(false); const [saveMessage,setSaveMessage]=useState("");
 useEffect(()=>{setSource(window.location.pathname==="/test"?"test":null);},[]);
 useEffect(()=>{if(!saveMessage)return;const timer=window.setTimeout(()=>setSaveMessage(""),4000);return()=>window.clearTimeout(timer);},[saveMessage]);
 useEffect(()=>{if(!source)return;const clickHandler=(event:MouseEvent)=>{const button=(event.target as HTMLElement).closest("button");if(!(button instanceof HTMLButtonElement))return;const questionId=findCurrentQuestionId();const answerCode=findAnswerCode(button);if(questionId&&answerCode){const answers=readAnswers();answers[questionId]=answerCode;sessionStorage.setItem(ANSWERS_KEY,JSON.stringify(answers));}const label=button.textContent??"";if(RETEST_LABELS.some(x=>label.includes(x))){sessionStorage.removeItem(ANSWERS_KEY);sessionStorage.removeItem(SESSION_KEY);sessionStorage.removeItem(SAVED_CODE_KEY);sessionStorage.removeItem(SAVED_SOURCE_KEY);sessionStorage.removeItem(SAVING_KEY);setBeautyCode(null);setShowAgePrompt(false);setSaveMessage("");}};
  const persistAnonymousTest=async(code:string)=>{const savedCode=sessionStorage.getItem(SAVED_CODE_KEY);const savedSource=sessionStorage.getItem(SAVED_SOURCE_KEY);const sessionId=sessionStorage.getItem(SESSION_KEY);if(savedCode===code&&savedSource==="test"&&sessionId)return;if(sessionStorage.getItem(SAVING_KEY)==="1")return;const answers=Object.entries(readAnswers()).map(([questionId,selectedCode])=>({questionId:Number(questionId),selectedCode}));if(answers.length!==20)return;sessionStorage.setItem(SAVING_KEY,"1");const payload={beautyCode:code,beautyCodeSource:"test" as const,ageBand:null,answers};try{const response=await fetch('/api/anonymous-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json() as {ok?:boolean;sessionId?:string;code?:string};if(!response.ok||!result.ok||!result.sessionId){if(result.code==='SUPABASE_NOT_CONFIGURED')localStorage.setItem('layad-pending-session',JSON.stringify(payload));return;}sessionStorage.setItem(SESSION_KEY,result.sessionId);sessionStorage.setItem(SAVED_CODE_KEY,code);sessionStorage.setItem(SAVED_SOURCE_KEY,'test');localStorage.removeItem('layad-pending-session');}catch{localStorage.setItem('layad-pending-session',JSON.stringify(payload));}finally{sessionStorage.removeItem(SAVING_KEY);}};
  const inspectResult=()=>{const code=findBeautyCode();if(!code)return;setBeautyCode(code);setShowAgePrompt(false);void persistAnonymousTest(code);};
  document.addEventListener('click',clickHandler);inspectResult();const observer=new MutationObserver(inspectResult);observer.observe(document.body,{childList:true,subtree:true});return()=>{document.removeEventListener('click',clickHandler);observer.disconnect();};
 },[source]);
 useEffect(()=>{const submitHandler=async(event:Event)=>{const form=event.target as HTMLFormElement;if(!(form instanceof HTMLFormElement))return;const submitButton=form.querySelector('button[type="submit"]');const label=submitButton?.textContent??"";if(!ANALYSIS_LABELS.some(x=>label.includes(x)))return;const sessionId=sessionStorage.getItem(SESSION_KEY);if(!sessionId){event.preventDefault();event.stopImmediatePropagation();const code=findBeautyCode();if(code){setBeautyCode(code);setSaveMessage("");setShowAgePrompt(false);}else setSaveMessage(t.chooseCode);return;}const input=form.querySelector('input') as HTMLInputElement|null;const inputValue=input?.value.trim();if(!inputValue)return;const inputType=/^https?:\/\//i.test(inputValue)?'url':'name';try{await fetch('/api/product-analysis-request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,inputType,inputValue})});}catch{}};document.addEventListener('submit',submitHandler,true);return()=>document.removeEventListener('submit',submitHandler,true);},[source,t.chooseCode]);
 const saveSession=async(ageBand:AgeBand|null)=>{if(!beautyCode||!source||saving)return;setSaving(true);setSaveMessage("");const answers=Object.entries(readAnswers()).map(([questionId,selectedCode])=>({questionId:Number(questionId),selectedCode}));const payload={beautyCode,beautyCodeSource:source,ageBand,answers};try{const response=await fetch('/api/anonymous-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json() as {ok?:boolean;sessionId?:string;code?:string};if(!response.ok||!result.ok||!result.sessionId){setShowAgePrompt(false);if(result.code==='SUPABASE_NOT_CONFIGURED'){localStorage.setItem('layad-pending-session',JSON.stringify(payload));setSaveMessage(t.pending);}else setSaveMessage(t.fail);return;}sessionStorage.setItem(SESSION_KEY,result.sessionId);sessionStorage.setItem(SAVED_CODE_KEY,beautyCode);sessionStorage.setItem(SAVED_SOURCE_KEY,source);localStorage.removeItem('layad-pending-session');setShowAgePrompt(false);setSaveMessage(t.saved);}catch{setShowAgePrompt(false);localStorage.setItem('layad-pending-session',JSON.stringify(payload));setSaveMessage(t.network);}finally{setSaving(false);}};
 if(!source||(!showAgePrompt&&!saveMessage))return null;
 return <>{showAgePrompt?<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/35 px-4"><section className="w-full max-w-md rounded-3xl bg-white p-6 text-[#382d2d] shadow-2xl sm:p-8"><p className="text-center text-xs font-semibold tracking-[0.18em] text-[#b97b88]">OPTIONAL</p><h2 className="mt-3 text-center text-xl font-semibold">{t.ageTitle}</h2><p className="mt-3 text-center text-sm leading-6 text-[#766767]">{t.ageDesc}</p><div className="mt-6 grid grid-cols-2 gap-2">{ageValues.map(value=><button key={value} type="button" disabled={saving} onClick={()=>saveSession(value)} className="rounded-2xl border border-[#ead7db] bg-[#fffafa] px-3 py-3 text-sm font-semibold transition hover:border-[#d88c9c] hover:bg-[#fff0f2] disabled:opacity-60">{t.ages[value]}</button>)}</div><button type="button" disabled={saving} onClick={()=>saveSession(null)} className="mt-4 w-full rounded-full px-4 py-3 text-sm text-[#7e7070] hover:bg-[#fff5f6] disabled:opacity-60">{t.skip}</button></section></div>:null}{saveMessage?<div className="fixed bottom-5 left-1/2 z-[110] flex w-[calc(100%-2rem)] max-w-md -translate-x-1/2 items-center gap-3 rounded-2xl bg-[#382d2d] px-5 py-4 text-sm text-white shadow-xl"><p className="min-w-0 flex-1 text-center">{saveMessage}</p><button type="button" aria-label={t.close} onClick={()=>setSaveMessage("")} className="shrink-0 rounded-full px-2 py-1 text-lg leading-none text-white/80 hover:bg-white/10 hover:text-white">×</button></div>:null}</>;
}
