"use client";

import { useEffect, useMemo, useState } from "react";

type Section="dashboard"|"statistics"|"requests"|"analysis"|"products"|"results"|"settings";
type Fit={beautyCode:string;fitScore:number;reviewCount:number;confidence:number;rank?:number};
type RequestRow={id:string;sessionId:string;value:string;inputType:"name"|"url";status:string;createdAt:string;beautyCode:string;productId:string|null;personalFit:Fit|null;bestFit:Fit|null;fits:Fit[]};
type ProductRow={name:string;count:number;uniqueSessions:number;topCode:string;status:string;productId:string|null;bestFit:Fit|null;fits:Fit[]};
type StatRow={key?:string;code?:string;label:string;count:number;topCode:string};
type Data={ok:boolean;message?:string;kpis?:{totalUsers:number;testCompleted:number;manualSelected:number;productRequests:number;requestedProducts:number;completedProducts:number};typeStats?:Array<{code:string;count:number}>;axes?:Record<string,number>;sourceRatio?:{test:number;manual:number};ageStats?:StatRow[];countryStats?:StatRow[];regionStats?:StatRow[];statusCounts?:Record<string,number>;topProducts?:ProductRow[];recentRequests?:RequestRow[];warnings?:string[]};

const codes=["OGPV","OGPE","OGCV","OGCE","OMPV","OMPE","OMCV","OMCE","DGPV","DGPE","DGCV","DGCE","DMPV","DMPE","DMCV","DMCE"];
const menu:Array<{id:Section;label:string;description:string}>=[
{id:"dashboard",label:"대시보드",description:"사용자 유형조회와 상품별 맞춤 적합도 현황을 한눈에 확인합니다."},
{id:"statistics",label:"사용자 통계 상세",description:"Beauty Code, 연령대, 국가·지역별 사용자 분포를 확인합니다."},
{id:"requests",label:"상품 신청 정보",description:"신청자 유형과 선택 상품의 맞춤 적합도 점수·등급·순위를 확인합니다."},
{id:"analysis",label:"분석 작업",description:"상품 신청을 검토하고 16유형 적합도 결과 입력 작업으로 연결합니다."},
{id:"products",label:"상품 관리",description:"상품별 16유형 점수분포와 적합도 히트맵을 비교합니다."},
{id:"results",label:"적합도 결과",description:"선택한 신청 상품의 16유형 점수를 입력하고 사용자 결과를 공개합니다."},
{id:"settings",label:"운영 설정",description:"관리자 접근과 데이터 운영 기준을 확인합니다."},
];
const statusLabel:Record<string,string>={submitted:"신청 접수",collecting_reviews:"상품 확인",insufficient_reviews:"분석 불가",analyzing:"분석 중",completed:"분석 완료",failed:"처리 실패"};
function grade(score:number){if(score>=90)return"매우 적합";if(score>=75)return"적합";if(score>=60)return"보통";if(score>=40)return"낮음";return"매우 낮음";}
function heat(score:number){return{backgroundColor:`rgba(216,140,156,${Math.max(.08,Math.min(.44,score/230))})`};}
function dateText(v:string){return new Intl.DateTimeFormat("ko-KR",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v));}
function Card({title,value,note}:{title:string;value:number|string;note?:string}){return <article className="rounded-2xl border border-[#eadfe1] bg-white p-5 shadow-sm"><p className="text-xs text-[#78696c]">{title}</p><p className="mt-2 text-2xl font-semibold">{value}</p>{note?<p className="mt-1 text-xs text-[#9a888c]">{note}</p>:null}</article>}
function Heatmap({fits,mine}:{fits:Fit[];mine?:string}){const best=[...fits].sort((a,b)=>b.fitScore-a.fitScore)[0];return <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{codes.map(code=>{const f=fits.find(x=>x.beautyCode===code);return <div key={code} style={f?heat(f.fitScore):undefined} className={`rounded-xl border p-3 text-center ${code===mine?"border-[#a94f65] ring-2 ring-[#a94f65]/20":"border-[#eadfe1]"}`}><div className="flex justify-center gap-1 text-xs font-semibold"><span>{code}</span>{code===mine?<span>회원</span>:code===best?.beautyCode?<span>최고</span>:null}</div><p className="mt-1 text-xl font-semibold">{f?f.fitScore:"—"}</p><p className="text-[11px] text-[#78696c]">{f?grade(f.fitScore):"미분석"}</p></div>})}</div>}

export default function AdminPage(){
 const[section,setSection]=useState<Section>("dashboard");const[mobile,setMobile]=useState(false);const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[selectedId,setSelectedId]=useState("");const[scores,setScores]=useState<Record<string,number>>(()=>Object.fromEntries(codes.map(c=>[c,0])));const[saveMessage,setSaveMessage]=useState("");const[saving,setSaving]=useState(false);
 const load=()=>{setLoading(true);fetch("/api/admin/dashboard",{cache:"no-store"}).then(r=>r.json()).then(setData).catch(()=>setData({ok:false,message:"관리자 API 연결 실패"})).finally(()=>setLoading(false));};useEffect(load,[]);
 const requests=data?.recentRequests??[];const products=data?.topProducts??[];const selected=requests.find(r=>r.id===selectedId)??requests.find(r=>r.status!=="completed")??requests[0];
 useEffect(()=>{if(selected&&!selectedId)setSelectedId(selected.id);},[selected,selectedId]);
 const fitBuckets=useMemo(()=>{const c={very:0,good:0,normal:0,low:0,pending:0};for(const r of requests){if(!r.personalFit)c.pending++;else if(r.personalFit.fitScore>=90)c.very++;else if(r.personalFit.fitScore>=75)c.good++;else if(r.personalFit.fitScore>=60)c.normal++;else c.low++;}return c;},[requests]);
 const save=async()=>{if(!selected)return;setSaving(true);setSaveMessage("");try{const r=await fetch("/api/admin/fit-result",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:selected.id,scores})});const p=await r.json();if(!r.ok||!p.ok)throw new Error(p.detail||p.message||p.code||"저장 실패");setSaveMessage("16유형 점수를 저장하고 사용자 결과를 공개했습니다.");await load();}catch(e){setSaveMessage(e instanceof Error?e.message:"저장 실패");}finally{setSaving(false)}};
 const current=menu.find(m=>m.id===section)??menu[0];
 const nav=<>{menu.map(m=><button key={m.id} onClick={()=>{setSection(m.id);setMobile(false)}} className={`w-full rounded-xl px-4 py-3 text-left text-sm ${section===m.id?"bg-[#d88c9c] font-semibold text-white":"text-white/75 hover:bg-white/10"}`}>{m.label}</button>)}</>;
 const requestCards=<div className="space-y-3">{requests.map(r=><article key={r.id} className="rounded-2xl border border-[#eadfe1] bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{r.value}</p><p className="mt-1 text-xs text-[#78696c]">신청자 {r.beautyCode} · {dateText(r.createdAt)}</p></div>{r.personalFit?<div className="text-right"><p className="text-2xl font-semibold text-[#a94f65]">{r.personalFit.fitScore}점</p><p className="text-xs">{grade(r.personalFit.fitScore)} · 16유형 중 {r.personalFit.rank}위</p></div>:<span className="rounded-full bg-[#f4e8ea] px-3 py-1 text-xs">{statusLabel[r.status]??r.status}</span>}</div>{r.personalFit&&r.bestFit?<p className="mt-3 rounded-xl bg-[#fff7f8] px-3 py-2 text-xs">최고 적합 {r.bestFit.beautyCode} {r.bestFit.fitScore}점 · 신청자 유형과 {Math.max(0,r.bestFit.fitScore-r.personalFit.fitScore)}점 차이</p>:null}</article>)}</div>;
 let body:React.ReactNode;
 if(section==="dashboard")body=<div className="space-y-7"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card title="전체 유형조회" value={data?.kpis?.totalUsers??0}/><Card title="상품 신청" value={data?.kpis?.productRequests??0}/><Card title="매우 적합 신청" value={fitBuckets.very}/><Card title="낮은 적합도 신청" value={fitBuckets.low}/><Card title="분석 대기" value={fitBuckets.pending}/></section><section className="grid gap-6 xl:grid-cols-[1.1fr_1fr]"><article className="rounded-3xl border border-[#eadfe1] bg-white p-6"><h3 className="text-lg font-semibold">최근 신청자의 상품 적합도</h3><p className="mt-2 text-sm text-[#78696c]">신청 건수보다 사용자 Beauty Code와 상품의 적합도를 우선 표시합니다.</p><div className="mt-5">{requestCards}</div></article><article className="rounded-3xl border border-[#eadfe1] bg-white p-6"><h3 className="text-lg font-semibold">상품별 최고 적합 유형</h3><div className="mt-5 space-y-3">{products.map(p=><div key={p.name} className="rounded-2xl border border-[#eadfe1] p-4"><p className="font-semibold">{p.name}</p><p className="mt-2 text-sm">신청 관심 1위 {p.topCode}</p><p className="mt-1 text-sm text-[#a94f65]">{p.bestFit?`적합도 최고 ${p.bestFit.beautyCode} ${p.bestFit.fitScore}점`:"16유형 점수 미등록"}</p></div>)}</div></article></section></div>;
 else if(section==="statistics")body=<div className="space-y-6"><section className="grid gap-3 sm:grid-cols-3"><Card title="전체 사용자" value={data?.kpis?.totalUsers??0}/><Card title="20문항 테스트" value={`${data?.sourceRatio?.test??0}%`}/><Card title="직접 선택" value={`${data?.sourceRatio?.manual??0}%`}/></section>{[["연령대 상세",data?.ageStats??[]],["국가 상세",data?.countryStats??[]],["대한민국 지역 상세",data?.regionStats??[]]].map(([title,rows])=><section key={title as string} className="rounded-3xl border border-[#eadfe1] bg-white p-6"><h3 className="text-lg font-semibold">{title as string}</h3><div className="mt-4 space-y-3">{(rows as StatRow[]).map(r=><div key={r.label} className="grid grid-cols-[110px_1fr_60px] items-center gap-3 text-sm"><span>{r.label}</span><div className="h-3 rounded-full bg-[#f0e4e6]"><div className="h-full rounded-full bg-[#d88c9c]" style={{width:`${Math.min(100,r.count*4)}%`}}/></div><span className="text-right">{r.count} · {r.topCode}</span></div>)}</div></section>)}</div>;
 else if(section==="requests")body=<section className="rounded-3xl border border-[#eadfe1] bg-white p-6"><h3 className="text-lg font-semibold">상품 신청별 맞춤 적합도</h3><p className="mt-2 text-sm text-[#78696c]">신청자 유형, 해당 유형 점수, 등급, 16유형 순위를 함께 확인합니다.</p><div className="mt-5">{requestCards}</div></section>;
 else if(section==="analysis")body=<div className="grid gap-5 lg:grid-cols-3">{["submitted","analyzing","completed"].map(s=><section key={s} className="rounded-3xl border border-[#eadfe1] bg-white p-5"><h3 className="font-semibold">{statusLabel[s]}</h3><div className="mt-4 space-y-3">{requests.filter(r=>r.status===s).map(r=><button key={r.id} onClick={()=>{setSelectedId(r.id);setSection("results")}} className="w-full rounded-2xl border border-[#eadfe1] p-4 text-left"><p className="font-medium">{r.value}</p><p className="mt-1 text-xs">{r.beautyCode} · {r.personalFit?`${r.personalFit.fitScore}점`:"점수 입력 필요"}</p></button>)}</div></section>)}</div>;
 else if(section==="products")body=<div className="space-y-6">{products.map(p=><section key={p.name} className="rounded-3xl border border-[#eadfe1] bg-white p-6"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-semibold">{p.name}</h3><p className="mt-1 text-sm text-[#78696c]">신청 {p.count}건 · 신청 관심 1위 {p.topCode}</p></div><p className="text-sm font-semibold text-[#a94f65]">{p.bestFit?`최고 ${p.bestFit.beautyCode} ${p.bestFit.fitScore}점`:"미분석"}</p></div><div className="mt-5"><Heatmap fits={p.fits}/></div></section>)}</div>;
 else if(section==="results")body=<div className="space-y-6"><section className="rounded-3xl border border-[#eadfe1] bg-white p-6"><label className="text-sm font-semibold">분석할 상품 신청</label><select value={selected?.id??""} onChange={e=>setSelectedId(e.target.value)} className="mt-2 w-full rounded-xl border border-[#dfd1d4] px-3 py-3">{requests.map(r=><option key={r.id} value={r.id}>{r.value} · 신청자 {r.beautyCode} · {statusLabel[r.status]??r.status}</option>)}</select>{selected?<div className="mt-4 rounded-2xl bg-[#fff7f8] p-4"><p className="font-semibold">핵심 검수 대상: {selected.beautyCode} 사용자와 이 상품의 적합도</p><p className="mt-1 text-sm text-[#78696c]">16개 점수를 모두 입력하면 해당 사용자 결과 화면에 점수·등급·순위·히트맵이 공개됩니다.</p></div>:null}<div className="mt-5"><Heatmap fits={codes.map(c=>({beautyCode:c,fitScore:scores[c],reviewCount:0,confidence:.7}))} mine={selected?.beautyCode}/></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{codes.map(c=><label key={c} className={`rounded-2xl border p-4 ${c===selected?.beautyCode?"border-[#a94f65] bg-[#fff7f8]":"border-[#eadfe1]"}`}><span className="text-sm font-semibold">{c}</span><input type="number" min={0} max={100} value={scores[c]} onChange={e=>setScores({...scores,[c]:Math.max(0,Math.min(100,Number(e.target.value)))})} className="mt-2 w-full rounded-xl border border-[#dfd1d4] px-3 py-2"/></label>)}</div><button disabled={!selected||saving} onClick={save} className="mt-5 rounded-xl bg-[#382d2d] px-5 py-3 font-semibold text-white disabled:opacity-50">{saving?"저장 중":"16유형 결과 저장 및 공개"}</button>{saveMessage?<p className="mt-3 text-sm text-[#a94f65]">{saveMessage}</p>:null}</section></div>;
 else body=<div className="grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-[#eadfe1] bg-white p-6"><h3 className="font-semibold">운영 방식</h3><p className="mt-4 text-sm leading-7">ChatGPT Plus에서 운영자가 상품을 분석하고, 관리자 화면에서 16유형 점수를 등록합니다. OpenAI API 비용은 사용하지 않습니다.</p></section><section className="rounded-3xl border border-[#eadfe1] bg-white p-6"><h3 className="font-semibold">보안 상태</h3><p className="mt-4 text-sm leading-7">현재 관리자 인증은 미적용 상태입니다. 외부 공개 전 관리자 로그인을 추가해야 합니다.</p></section></div>;
 return <main className="min-h-screen bg-[#f7f4f4] text-[#382d2d]"><div className="mx-auto flex min-h-screen max-w-[1600px]"><aside className="hidden w-64 shrink-0 bg-[#2f2829] px-5 py-7 text-white lg:block"><button onClick={()=>setSection("dashboard")} className="text-left"><p className="text-2xl font-semibold tracking-[.18em] text-[#f4d4da]">LAYAD</p><p className="mt-2 text-sm text-white/70">관리자 화면</p></button><nav className="mt-8 space-y-2">{nav}</nav></aside><section className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex items-center justify-between border-b border-[#eadfe1] bg-white/95 px-5 py-4 sm:px-8"><div><p className="text-lg font-semibold tracking-[.16em] text-[#b97b88]">LAYAD</p><h1 className="mt-1 text-xl font-semibold">{current.label}</h1><p className="mt-1 hidden text-sm text-[#78696c] sm:block">{current.description}</p></div><button onClick={()=>setMobile(true)} className="rounded-xl border border-[#eadfe1] px-4 py-3 text-lg lg:hidden" aria-label="관리자 메뉴 열기">☰</button></header>{mobile?<div className="fixed inset-0 z-40 bg-black/40 lg:hidden" onClick={()=>setMobile(false)}><aside className="h-full w-[82%] max-w-sm bg-[#2f2829] p-5 text-white" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-xl font-semibold tracking-[.16em] text-[#f4d4da]">LAYAD</p><p className="mt-1 text-sm text-white/70">관리자 화면</p></div><button onClick={()=>setMobile(false)} className="text-2xl">×</button></div><nav className="mt-7 space-y-2">{nav}</nav></aside></div>:null}<div className="p-5 sm:p-8">{loading?<p>데이터를 불러오는 중입니다.</p>:!data?.ok?<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{data?.message??"관리자 데이터를 불러오지 못했습니다."}</div>:body}</div></section></div></main>;
}
