import { NextResponse } from "next/server";

const BEAUTY_CODES = ["OGPV","OGPE","OGCV","OGCE","OMPV","OMPE","OMCV","OMCE","DGPV","DGPE","DGCV","DGCE","DMPV","DMPE","DMCV","DMCE"] as const;
const REGION_NAMES: Record<string, string> = {"11":"서울","26":"부산","27":"대구","28":"인천","29":"광주","30":"대전","31":"울산","41":"경기","42":"강원","43":"충북","44":"충남","45":"전북","46":"전남","47":"경북","48":"경남","50":"제주","13":"도쿄","CA":"캘리포니아","NY":"뉴욕"};

function config(){return{url:process.env.SUPABASE_URL??process.env.NEXT_PUBLIC_SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY??process.env.SUPABASE_SECRET_KEY};}
function authHeaders(key:string):Record<string,string>{const headers:Record<string,string>={apikey:key};if(!key.startsWith("sb_secret_"))headers.Authorization=`Bearer ${key}`;return headers;}
async function readTable<T>(url:string,key:string,path:string):Promise<T>{const r=await fetch(`${url}/rest/v1/${path}`,{headers:authHeaders(key),cache:"no-store"});if(!r.ok)throw new Error(`Supabase read failed: ${r.status} ${await r.text()}`);return await r.json() as T;}
async function optional<T>(url:string,key:string,path:string,fallback:T){try{return{data:await readTable<T>(url,key,path),warning:null as string|null};}catch(e){return{data:fallback,warning:e instanceof Error?e.message:"조회 실패"};}}
function normalize(value:string){try{return new URL(value).hostname.replace(/^www\./,"");}catch{return value.trim().replace(/\s+/g," ").slice(0,80);}}
function topCode(rows:Array<{beauty_code:string|null}>){const c:Record<string,number>={};for(const r of rows)if(r.beauty_code)c[r.beauty_code]=(c[r.beauty_code]??0)+1;return Object.entries(c).sort((a,b)=>b[1]-a[1])[0]?.[0]??"-";}

export async function GET(){
 const {url,key}=config();if(!url||!key)return NextResponse.json({ok:false,code:"SUPABASE_NOT_CONFIGURED"},{status:503});
 try{
  const sessions=await readTable<Array<{id:string;beauty_code:string|null;beauty_code_source:"test"|"manual";age_band:string|null;country_code:string|null;region_code:string|null;created_at:string;completed:boolean}>>(url,key,"test_sessions?select=id,beauty_code,beauty_code_source,age_band,country_code,region_code,created_at,completed&order=created_at.desc&limit=10000");
  const requestResult=await optional<Array<{id:string;session_id:string;input_type:"name"|"url";input_value:string;status:string;created_at:string;product_id:string|null}>>(url,key,"product_analysis_requests?select=id,session_id,input_type,input_value,status,created_at,product_id&order=created_at.desc&limit=10000",[]);
  const fitResult=await optional<Array<{product_id:string;beauty_code:string;fit_score:number;review_count:number;confidence:number}>>(url,key,"product_type_fits?select=product_id,beauty_code,fit_score,review_count,confidence&limit=10000",[]);
  const productResult=await optional<Array<{id:string;canonical_name:string|null;brand:string|null;category:string|null}>>(url,key,"products?select=id,canonical_name,brand,category&limit=10000",[]);
  const requests=requestResult.data;const completedSessions=sessions.filter(s=>s.completed&&s.beauty_code);const sessionCode=new Map(completedSessions.map(s=>[s.id,s.beauty_code]));
  const testCount=completedSessions.filter(s=>s.beauty_code_source==="test").length;const manualCount=completedSessions.filter(s=>s.beauty_code_source==="manual").length;
  const typeCounts=Object.fromEntries(BEAUTY_CODES.map(c=>[c,0])) as Record<string,number>;const axisCounts:Record<string,number>={O:0,D:0,G:0,M:0,P:0,C:0,V:0,E:0};
  for(const s of completedSessions){if(s.beauty_code&&s.beauty_code in typeCounts)typeCounts[s.beauty_code]++;for(const l of s.beauty_code??"")if(l in axisCounts)axisCounts[l]++;}
  const ageOrder=["14-19","20-29","30-39","40-49","50-59","60+","prefer_not_to_say"];const ageLabels:Record<string,string>={"14-19":"14–19세","20-29":"20–29세","30-39":"30–39세","40-49":"40–49세","50-59":"50–59세","60+":"60세 이상","prefer_not_to_say":"응답하지 않음"};
  const ageStats=ageOrder.map(a=>{const rows=completedSessions.filter(s=>(s.age_band??"prefer_not_to_say")===a);return{key:a,label:ageLabels[a],count:rows.length,topCode:topCode(rows)};});
  const countryNames:Record<string,string>={KR:"대한민국",JP:"일본",US:"미국"};const countryMap=new Map<string,typeof completedSessions>();for(const r of completedSessions){const c=r.country_code??"UNKNOWN";countryMap.set(c,[...(countryMap.get(c)??[]),r]);}
  const countryStats=[...countryMap.entries()].map(([code,rows])=>({code,label:countryNames[code]??(code==="UNKNOWN"?"국가 확인 불가":code),count:rows.length,topCode:topCode(rows)})).sort((a,b)=>b.count-a.count);
  const regionMap=new Map<string,typeof completedSessions>();for(const r of completedSessions.filter(s=>s.country_code==="KR")){const c=r.region_code??"UNKNOWN";regionMap.set(c,[...(regionMap.get(c)??[]),r]);}
  const regionStats=[...regionMap.entries()].map(([code,rows])=>({code,label:REGION_NAMES[code]??(code==="UNKNOWN"?"지역 확인 불가":code),count:rows.length,topCode:topCode(rows)})).sort((a,b)=>b.count-a.count);
  const productById=new Map(productResult.data.map(p=>[p.id,p]));void productById;const fitsByProduct=new Map<string,Array<{beautyCode:string;fitScore:number;reviewCount:number;confidence:number}>>();
  for(const f of fitResult.data){const rows=fitsByProduct.get(f.product_id)??[];rows.push({beautyCode:f.beauty_code,fitScore:Math.round(Number(f.fit_score)),reviewCount:f.review_count,confidence:Number(f.confidence)});fitsByProduct.set(f.product_id,rows);}
  const groupMap=new Map<string,{name:string;count:number;sessions:Set<string>;statuses:Record<string,number>;types:Record<string,number>;productId:string|null}>();
  for(const r of requests){const keyName=(r.product_id??normalize(r.input_value).toLowerCase());const g=groupMap.get(keyName)??{name:normalize(r.input_value),count:0,sessions:new Set<string>(),statuses:{},types:{},productId:r.product_id};g.count++;g.sessions.add(r.session_id);g.statuses[r.status]=(g.statuses[r.status]??0)+1;const code=sessionCode.get(r.session_id);if(code)g.types[code]=(g.types[code]??0)+1;if(!g.productId&&r.product_id)g.productId=r.product_id;groupMap.set(keyName,g);}
  const topProducts=[...groupMap.values()].sort((a,b)=>b.count-a.count).slice(0,8).map(g=>{const fits=g.productId?(fitsByProduct.get(g.productId)??[]):[];const best=[...fits].sort((a,b)=>b.fitScore-a.fitScore)[0];return{name:g.name,count:g.count,uniqueSessions:g.sessions.size,topCode:Object.entries(g.types).sort((a,b)=>b[1]-a[1])[0]?.[0]??"-",status:Object.entries(g.statuses).sort((a,b)=>b[1]-a[1])[0]?.[0]??"submitted",productId:g.productId,bestFit:best??null,fits};});
  const statusCounts=requests.reduce<Record<string,number>>((a,r)=>(a[r.status]=(a[r.status]??0)+1,a),{});
  const recentRequests=requests.slice(0,30).map(r=>{const beautyCode=sessionCode.get(r.session_id)??"-";const fits=r.product_id?(fitsByProduct.get(r.product_id)??[]):[];const sorted=[...fits].sort((a,b)=>b.fitScore-a.fitScore);const mine=sorted.find(f=>f.beautyCode===beautyCode);return{id:r.id,sessionId:r.session_id,value:normalize(r.input_value),inputType:r.input_type,status:r.status,createdAt:r.created_at,beautyCode,productId:r.product_id,personalFit:mine?{...mine,rank:sorted.findIndex(f=>f.beautyCode===beautyCode)+1}:null,bestFit:sorted[0]??null,fits};});
  return NextResponse.json({ok:true,kpis:{totalUsers:completedSessions.length,testCompleted:testCount,manualSelected:manualCount,productRequests:requests.length,requestedProducts:groupMap.size,completedProducts:new Set(fitResult.data.map(f=>f.product_id)).size},typeStats:BEAUTY_CODES.map(code=>({code,count:typeCounts[code]})),axes:axisCounts,sourceRatio:{test:completedSessions.length?Math.round(testCount/completedSessions.length*100):0,manual:completedSessions.length?Math.round(manualCount/completedSessions.length*100):0},ageStats,countryStats,regionStats,statusCounts,topProducts,recentRequests,products:productResult.data.map(p=>({...p,fits:fitsByProduct.get(p.id)??[]})),warnings:[requestResult.warning?"상품 신청 테이블을 확인해 주세요.":null,fitResult.warning?"적합도 결과 테이블을 확인해 주세요.":null,productResult.warning?"상품 테이블을 확인해 주세요.":null].filter(Boolean)});
 }catch(e){return NextResponse.json({ok:false,code:"DASHBOARD_READ_FAILED",message:(e instanceof Error?e.message:"Unknown").slice(0,500)},{status:500});}
}
