"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Post={id:string;beauty_code:string;category:string;title:string;content:string;product_url:string|null;image_url:string|null;like_count:number;comment_count:number;created_at:string};
type Comment={id:string;beauty_code:string;content:string;created_at:string};
const codes=["OGPV","OGPE","OGCV","OGCE","OMPV","OMPE","OMCV","OMCE","DGPV","DGPE","DGCV","DGCE","DMPV","DMPE","DMCV","DMCE"];
const cats=["제품추천","사용후기","메이크업팁","질문","자유"];
function ensureToken(){let t=localStorage.getItem("layad-community-token");if(!t){t=crypto.randomUUID();localStorage.setItem("layad-community-token",t);}return t;}
export default function CommunityPage(){
 const [code,setCode]=useState(""); const [filter,setFilter]=useState("ALL"); const [posts,setPosts]=useState<Post[]>([]); const [busy,setBusy]=useState(false); const [write,setWrite]=useState(false); const [selected,setSelected]=useState<Post|null>(null); const [comments,setComments]=useState<Comment[]>([]); const [comment,setComment]=useState(""); const [form,setForm]=useState({category:"사용후기",title:"",content:"",product_url:"",image_url:""});
 useEffect(()=>{const saved=localStorage.getItem("layad-beauty-code")||localStorage.getItem("beautyCode")||"";if(codes.includes(saved.toUpperCase()))setCode(saved.toUpperCase());ensureToken();},[]);
 async function load(c=filter){const r=await fetch(`/api/community?code=${c}`,{cache:"no-store"});const j=await r.json();if(j.ok)setPosts(j.posts??[]);} useEffect(()=>{load(filter)},[filter]);
 async function submitPost(){if(!code)return;setBusy(true);const r=await fetch('/api/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'post',author_token:ensureToken(),beauty_code:code,...form})});const j=await r.json();setBusy(false);if(j.ok){setWrite(false);setForm({category:"사용후기",title:"",content:"",product_url:"",image_url:""});await load();}else alert(j.message||'저장 실패');}
 async function openPost(p:Post){setSelected(p);const r=await fetch(`/api/community?post=${p.id}`,{cache:'no-store'});const j=await r.json();if(j.ok)setComments(j.comments??[]);}
 async function action(name:string,p:Post){if(!code)return;const r=await fetch('/api/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:name,post_id:p.id,author_token:ensureToken(),beauty_code:code,comment_count:p.comment_count,content:name==='comment'?comment:undefined})});const j=await r.json();if(j.ok){if(name==='comment'){setComment('');await openPost({...p,comment_count:p.comment_count+1});}await load();if(name==='report')alert('신고가 접수되었습니다.');}}
 const myLabel=code||"Beauty Code 미설정";
 return <main className="min-h-screen bg-[#F6F4F0] text-[#222]">
  <header className="sticky top-0 z-20 border-b border-[#ddd6cd] bg-[#F6F4F0]/95 px-4 py-4 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center justify-between"><div><p className="text-xs font-semibold tracking-[.16em] text-[#9b726f]">LAYAD BEAUTY COMMUNITY</p><h1 className="mt-1 text-xl font-semibold">16 Codes Beauty Talk</h1></div><Link href="/" className="text-sm font-semibold">홈</Link></div></header>
  <div className="mx-auto max-w-5xl px-4 py-6">
   {!code?<section className="rounded-3xl border border-[#ded6cc] bg-white p-6"><h2 className="text-xl font-semibold">내 Beauty Code를 선택해 주세요</h2><p className="mt-2 text-sm text-[#6f6963]">테스트를 완료한 사용자는 코드가 자동 연결됩니다. 아직 연결되지 않았다면 한 번만 선택하면 이 기기에 저장됩니다.</p><div className="mt-5 grid grid-cols-4 gap-2 sm:grid-cols-8">{codes.map(c=><button key={c} onClick={()=>{setCode(c);localStorage.setItem('layad-beauty-code',c)}} className="rounded-xl border border-[#d9d0c6] bg-[#faf8f5] px-2 py-3 text-sm font-semibold">{c}</button>)}</div></section>:<>
    <section className="flex flex-col gap-4 rounded-3xl border border-[#ded6cc] bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs text-[#8c837a]">MY BEAUTY CODE</p><p className="mt-1 text-2xl font-bold">{myLabel}</p></div><button onClick={()=>setWrite(true)} className="rounded-full bg-[#222] px-6 py-3 text-sm font-semibold text-white">뷰티 정보 공유하기</button></section>
    <div className="mt-5 flex gap-2 overflow-x-auto pb-2"><button onClick={()=>setFilter('ALL')} className={`shrink-0 rounded-full px-4 py-2 text-sm ${filter==='ALL'?'bg-[#222] text-white':'bg-white'}`}>전체</button>{codes.map(c=><button key={c} onClick={()=>setFilter(c)} className={`shrink-0 rounded-full px-4 py-2 text-sm ${filter===c?'bg-[#222] text-white':'bg-white'}`}>{c}</button>)}</div>
    <section className="mt-4 space-y-3">{posts.length?posts.map(p=><article key={p.id} onClick={()=>openPost(p)} className="cursor-pointer rounded-3xl border border-[#e0d9d0] bg-white p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="rounded-full bg-[#f1e7e5] px-3 py-1 text-xs font-bold text-[#8d5555]">{p.beauty_code}</span><span className="text-xs text-[#837b73]">{p.category}</span></div><span className="text-xs text-[#9a938c]">{new Date(p.created_at).toLocaleDateString('ko-KR')}</span></div><h2 className="mt-3 text-lg font-semibold">{p.title}</h2><p className="mt-2 line-clamp-3 whitespace-pre-wrap text-sm leading-6 text-[#5f5953]">{p.content}</p>{p.product_url?<p className="mt-3 truncate text-xs text-[#9b726f]">상품 링크 · {p.product_url}</p>:null}<div className="mt-4 flex gap-4 text-xs text-[#7e7770]"><span>♥ {p.like_count}</span><span>댓글 {p.comment_count}</span></div></article>):<div className="rounded-3xl bg-white p-10 text-center text-sm text-[#877f77]">아직 등록된 글이 없습니다. 첫 뷰티 정보를 공유해 보세요.</div>}</section>
   </>}
  </div>
  {write&&<div className="fixed inset-0 z-40 flex items-end bg-black/35 sm:items-center sm:justify-center"><div className="max-h-[90vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 sm:max-w-xl sm:rounded-3xl"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">뷰티 정보 공유</h2><button onClick={()=>setWrite(false)}>닫기</button></div><p className="mt-2 text-sm">작성자 Beauty Code <b>{code}</b></p><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="mt-5 w-full rounded-xl border p-3">{cats.map(x=><option key={x}>{x}</option>)}</select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="제목" className="mt-3 w-full rounded-xl border p-3"/><textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})} placeholder="제품 사용 경험, 메이크업 팁, 질문을 공유해 주세요." rows={7} className="mt-3 w-full rounded-xl border p-3"/><input value={form.product_url} onChange={e=>setForm({...form,product_url:e.target.value})} placeholder="상품 링크 (선택)" className="mt-3 w-full rounded-xl border p-3"/><input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="이미지 URL (선택)" className="mt-3 w-full rounded-xl border p-3"/><button disabled={busy} onClick={submitPost} className="mt-4 w-full rounded-full bg-[#222] py-3.5 font-semibold text-white disabled:opacity-50">등록하기</button></div></div>}
  {selected&&<div className="fixed inset-0 z-40 flex items-end bg-black/35 sm:items-center sm:justify-center"><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 sm:max-w-2xl sm:rounded-3xl"><div className="flex justify-between"><div><span className="rounded-full bg-[#f1e7e5] px-3 py-1 text-xs font-bold">{selected.beauty_code}</span><span className="ml-2 text-xs text-[#777]">{selected.category}</span></div><button onClick={()=>setSelected(null)}>닫기</button></div><h2 className="mt-4 text-2xl font-semibold">{selected.title}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7">{selected.content}</p>{selected.product_url?<a href={selected.product_url} target="_blank" rel="noreferrer" className="mt-4 block text-sm font-semibold text-[#9b5d62]">상품 링크 열기</a>:null}{selected.image_url?<img src={selected.image_url} alt="게시글 이미지" className="mt-4 max-h-80 w-full rounded-2xl object-cover"/>:null}<div className="mt-5 flex gap-3"><button onClick={()=>action('like',selected)} className="rounded-full border px-4 py-2 text-sm">♥ 좋아요</button><button onClick={()=>action('report',selected)} className="rounded-full border px-4 py-2 text-sm text-[#a05c5c]">신고</button></div><div className="mt-6 border-t pt-5"><h3 className="font-semibold">댓글 {comments.length}</h3><div className="mt-3 space-y-3">{comments.map(c=><div key={c.id} className="rounded-2xl bg-[#f8f5f1] p-3"><b className="text-xs">{c.beauty_code}</b><p className="mt-1 text-sm">{c.content}</p></div>)}</div><div className="mt-4 flex gap-2"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="댓글 입력" className="min-w-0 flex-1 rounded-full border px-4 py-3 text-sm"/><button onClick={()=>action('comment',selected)} className="rounded-full bg-[#222] px-4 text-sm font-semibold text-white">등록</button></div></div></div></div>}
 </main>
}
