"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { LanguageSwitcher, useLanguage } from "@/app/i18n";
import { localeDate } from "@/lib/beauty-code-labels";

type Post={id:string;beauty_code:string;category:string;title:string;content:string;product_url:string|null;image_url:string|null;like_count:number;comment_count:number;created_at:string};
type Comment={id:string;beauty_code:string;content:string;created_at:string};
const codes=["OGPV","OGPE","OGCV","OGCE","OMPV","OMPE","OMCV","OMCE","DGPV","DGPE","DGCV","DGCE","DMPV","DMPE","DMCV","DMCE"];
const cats=["제품추천","사용후기","메이크업팁","질문","자유"];
const categoryCopy={
 ko:{제품추천:"제품추천",사용후기:"사용후기",메이크업팁:"메이크업팁",질문:"질문",자유:"자유"},
 en:{제품추천:"Product picks",사용후기:"Reviews",메이크업팁:"Makeup tips",질문:"Questions",자유:"Free talk"},
 ja:{제품추천:"商品おすすめ",사용후기:"使用レビュー",메이크업팁:"メイクのコツ",질문:"質問",자유:"フリートーク"},
} as const;
const copy={
 ko:{home:"홈",choose:"내 Beauty Code를 선택해 주세요",chooseDesc:"테스트를 완료한 사용자는 코드가 자동 연결됩니다. 아직 연결되지 않았다면 한 번만 선택하면 이 기기에 저장됩니다.",unset:"Beauty Code 미설정",share:"뷰티 정보 공유하기",all:"전체",empty:"아직 등록된 글이 없습니다. 첫 뷰티 정보를 공유해 보세요.",productLink:"상품 링크",comments:"댓글",write:"뷰티 정보 공유",close:"닫기",author:"작성자 Beauty Code",title:"제목",content:"제품 사용 경험, 메이크업 팁, 질문을 공유해 주세요.",productOptional:"상품 링크 (선택)",imageOptional:"이미지 URL (선택)",submit:"등록하기",openLink:"상품 링크 열기",like:"좋아요",report:"신고",commentPlaceholder:"댓글 입력",saveFail:"저장 실패",reported:"신고가 접수되었습니다.",loginTitle:"로그인하고 LAYAD Community에 참여하세요",loginDesc:"로그인하면 내 Beauty Code와 활동 기록을 안전하게 이어서 사용할 수 있습니다.",loginCta:"로그인 · 회원가입",logged:"내 Beauty Code로 참여 중"},
 en:{home:"Home",choose:"Choose your Beauty Code",chooseDesc:"If you have completed the test, your code is linked automatically. Otherwise, choose it once and it will be kept on this device.",unset:"Beauty Code not set",share:"Share beauty info",all:"All",empty:"No posts yet. Be the first to share a beauty tip.",productLink:"Product link",comments:"Comments",write:"Share beauty info",close:"Close",author:"Author Beauty Code",title:"Title",content:"Share a product experience, makeup tip, or question.",productOptional:"Product link (optional)",imageOptional:"Image URL (optional)",submit:"Post",openLink:"Open product link",like:"Like",report:"Report",commentPlaceholder:"Write a comment",saveFail:"Could not save",reported:"Report submitted.",loginTitle:"Sign in to join the LAYAD Community",loginDesc:"Sign in to keep your Beauty Code and community activity connected across visits.",loginCta:"Sign in · Sign up",logged:"Participating with my Beauty Code"},
 ja:{home:"ホーム",choose:"Beauty Codeを選択してください",chooseDesc:"テストを完了した場合はコードが自動で連携されます。まだ連携されていない場合は一度選ぶとこの端末に保存されます。",unset:"Beauty Code未設定",share:"ビューティー情報を共有",all:"すべて",empty:"まだ投稿がありません。最初のビューティー情報を共有してみましょう。",productLink:"商品リンク",comments:"コメント",write:"ビューティー情報を共有",close:"閉じる",author:"投稿者 Beauty Code",title:"タイトル",content:"商品使用体験、メイクのコツ、質問を共有してください。",productOptional:"商品リンク（任意）",imageOptional:"画像URL（任意）",submit:"投稿する",openLink:"商品リンクを開く",like:"いいね",report:"通報",commentPlaceholder:"コメントを入力",saveFail:"保存できませんでした",reported:"通報を受け付けました。",loginTitle:"ログインしてLAYAD Communityに参加",loginDesc:"ログインするとBeauty Codeとコミュニティ活動を継続して利用できます。",loginCta:"ログイン · 会員登録",logged:"自分のBeauty Codeで参加中"},
} as const;
function ensureToken(){let t=localStorage.getItem("layad-community-token");if(!t){t=crypto.randomUUID();localStorage.setItem("layad-community-token",t);}return t;}

export default function CommunityPage(){
 const {locale}=useLanguage(); const t=copy[locale];
 const [code,setCode]=useState(""); const [filter,setFilter]=useState("ALL"); const [posts,setPosts]=useState<Post[]>([]); const [busy,setBusy]=useState(false); const [write,setWrite]=useState(false); const [selected,setSelected]=useState<Post|null>(null); const [comments,setComments]=useState<Comment[]>([]); const [comment,setComment]=useState(""); const [signedIn,setSignedIn]=useState(false); const [form,setForm]=useState({category:"사용후기",title:"",content:"",product_url:"",image_url:""});
 useEffect(()=>{(async()=>{let saved=localStorage.getItem("layad-beauty-code")||localStorage.getItem("beautyCode")||"";try{const r=await fetch('/api/mypage',{cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok&&j.ok){setSignedIn(true);const current=(j.codes??[]).find((x:{is_current?:boolean})=>x.is_current)??j.codes?.[0];if(current?.beauty_code)saved=current.beauty_code;}}catch{}if(codes.includes(saved.toUpperCase()))setCode(saved.toUpperCase());ensureToken();})();},[]);
 async function load(c=filter){const r=await fetch(`/api/community?code=${c}`,{cache:"no-store"});const j=await r.json();if(j.ok)setPosts(j.posts??[]);} useEffect(()=>{void load(filter)},[filter]);
 async function submitPost(){if(!code)return;setBusy(true);const r=await fetch('/api/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'post',author_token:ensureToken(),beauty_code:code,...form})});const j=await r.json();setBusy(false);if(j.ok){setWrite(false);setForm({category:"사용후기",title:"",content:"",product_url:"",image_url:""});await load();}else alert(t.saveFail);}
 async function openPost(p:Post){setSelected(p);const r=await fetch(`/api/community?post=${p.id}`,{cache:'no-store'});const j=await r.json();if(j.ok)setComments(j.comments??[]);}
 async function action(name:string,p:Post){if(!code)return;const r=await fetch('/api/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:name,post_id:p.id,author_token:ensureToken(),beauty_code:code,comment_count:p.comment_count,content:name==='comment'?comment:undefined})});const j=await r.json();if(j.ok){if(name==='comment'){setComment('');await openPost({...p,comment_count:p.comment_count+1});}await load();if(name==='report')alert(t.reported);}}
 const myLabel=code||t.unset;
 return <main className="min-h-screen bg-[#F6F4F0] pb-24 text-[#222]">
  <header className="sticky top-0 z-20 border-b border-[#ddd6cd] bg-[#F6F4F0]/95 px-4 py-4 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center justify-between gap-3"><div><p className="text-xs font-semibold tracking-[.16em] text-[#9b726f]">LAYAD BEAUTY COMMUNITY</p><h1 className="mt-1 text-xl font-semibold">16 Codes Beauty Talk</h1></div><div className="flex items-center gap-3"><LanguageSwitcher compact/><Link href="/" className="text-sm font-semibold">{t.home}</Link></div></div></header>
  <div className="mx-auto max-w-5xl px-4 py-6">
   {!signedIn?<section className="mb-5 rounded-3xl border border-[#edcbd2] bg-[#fff7f8] p-5"><p className="text-xs font-bold tracking-[.14em] text-[#b66f7f]">LAYAD ACCOUNT</p><h2 className="mt-2 text-lg font-semibold">{t.loginTitle}</h2><p className="mt-2 text-sm leading-6 text-[#716368]">{t.loginDesc}</p><Link href="/account" className="mt-4 inline-flex rounded-full bg-[#d88c9c] px-5 py-2.5 text-sm font-semibold text-white">{t.loginCta}</Link></section>:<p className="mb-4 text-sm font-semibold text-[#8f666d]">✓ {t.logged}</p>}
   {!code?<section className="rounded-3xl border border-[#ded6cc] bg-white p-6"><h2 className="text-xl font-semibold">{t.choose}</h2><p className="mt-2 text-sm leading-6 text-[#6f6963]">{t.chooseDesc}</p><div className="mt-5 grid grid-cols-4 gap-2 sm:grid-cols-8">{codes.map(c=><button key={c} onClick={()=>{setCode(c);localStorage.setItem('layad-beauty-code',c)}} className="rounded-xl border border-[#d9d0c6] bg-[#faf8f5] px-2 py-3 text-sm font-semibold">{c}</button>)}</div></section>:<>
    <section className="flex flex-col gap-4 rounded-3xl border border-[#ded6cc] bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs text-[#8c837a]">MY BEAUTY CODE</p><p className="mt-1 text-2xl font-bold">{myLabel}</p></div><button onClick={()=>setWrite(true)} className="rounded-full bg-[#222] px-6 py-3 text-sm font-semibold text-white">{t.share}</button></section>
    <div className="mt-5 flex gap-2 overflow-x-auto pb-2"><button onClick={()=>setFilter('ALL')} className={`shrink-0 rounded-full px-4 py-2 text-sm ${filter==='ALL'?'bg-[#222] text-white':'bg-white'}`}>{t.all}</button>{codes.map(c=><button key={c} onClick={()=>setFilter(c)} className={`shrink-0 rounded-full px-4 py-2 text-sm ${filter===c?'bg-[#222] text-white':'bg-white'}`}>{c}</button>)}</div>
    <section className="mt-4 space-y-3">{posts.length?posts.map(p=><article key={p.id} onClick={()=>openPost(p)} className="cursor-pointer rounded-3xl border border-[#e0d9d0] bg-white p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="rounded-full bg-[#f1e7e5] px-3 py-1 text-xs font-bold text-[#8d5555]">{p.beauty_code}</span><span className="text-xs text-[#837b73]">{categoryCopy[locale][p.category as keyof typeof categoryCopy.ko]??p.category}</span></div><span className="text-xs text-[#9a938c]">{localeDate(p.created_at,locale)}</span></div><h2 className="mt-3 text-lg font-semibold">{p.title}</h2><p className="mt-2 line-clamp-3 whitespace-pre-wrap text-sm leading-6 text-[#5f5953]">{p.content}</p>{p.product_url?<p className="mt-3 truncate text-xs text-[#9b726f]">{t.productLink} · {p.product_url}</p>:null}<div className="mt-4 flex gap-4 text-xs text-[#7e7770]"><span>♥ {p.like_count}</span><span>{t.comments} {p.comment_count}</span></div></article>):<div className="rounded-3xl bg-white p-10 text-center text-sm text-[#877f77]">{t.empty}</div>}</section>
   </>}
  </div>
  {write&&<div className="fixed inset-0 z-40 flex items-end bg-black/35 sm:items-center sm:justify-center"><div className="max-h-[90vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 sm:max-w-xl sm:rounded-3xl"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{t.write}</h2><button onClick={()=>setWrite(false)}>{t.close}</button></div><p className="mt-2 text-sm">{t.author} <b>{code}</b></p><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="mt-5 w-full rounded-xl border p-3">{cats.map(x=><option key={x} value={x}>{categoryCopy[locale][x as keyof typeof categoryCopy.ko]}</option>)}</select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder={t.title} className="mt-3 w-full rounded-xl border p-3"/><textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})} placeholder={t.content} rows={7} className="mt-3 w-full rounded-xl border p-3"/><input value={form.product_url} onChange={e=>setForm({...form,product_url:e.target.value})} placeholder={t.productOptional} className="mt-3 w-full rounded-xl border p-3"/><input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder={t.imageOptional} className="mt-3 w-full rounded-xl border p-3"/><button disabled={busy} onClick={submitPost} className="mt-4 w-full rounded-full bg-[#222] py-3.5 font-semibold text-white disabled:opacity-50">{t.submit}</button></div></div>}
  {selected&&<div className="fixed inset-0 z-40 flex items-end bg-black/35 sm:items-center sm:justify-center"><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 sm:max-w-2xl sm:rounded-3xl"><div className="flex justify-between"><div><span className="rounded-full bg-[#f1e7e5] px-3 py-1 text-xs font-bold">{selected.beauty_code}</span><span className="ml-2 text-xs text-[#777]">{categoryCopy[locale][selected.category as keyof typeof categoryCopy.ko]??selected.category}</span></div><button onClick={()=>setSelected(null)}>{t.close}</button></div><h2 className="mt-4 text-2xl font-semibold">{selected.title}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7">{selected.content}</p>{selected.product_url?<a href={selected.product_url} target="_blank" rel="noreferrer" className="mt-4 block text-sm font-semibold text-[#9b5d62]">{t.openLink}</a>:null}{selected.image_url?<img src={selected.image_url} alt="Community post" className="mt-4 max-h-80 w-full rounded-2xl object-cover"/>:null}<div className="mt-5 flex gap-3"><button onClick={()=>action('like',selected)} className="rounded-full border px-4 py-2 text-sm">♥ {t.like}</button><button onClick={()=>action('report',selected)} className="rounded-full border px-4 py-2 text-sm text-[#a05c5c]">{t.report}</button></div><div className="mt-6 border-t pt-5"><h3 className="font-semibold">{t.comments} {comments.length}</h3><div className="mt-3 space-y-3">{comments.map(c=><div key={c.id} className="rounded-2xl bg-[#f8f5f1] p-3"><b className="text-xs">{c.beauty_code}</b><p className="mt-1 text-sm">{c.content}</p></div>)}</div><div className="mt-4 flex gap-2"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder={t.commentPlaceholder} className="min-w-0 flex-1 rounded-full border px-4 py-3 text-sm"/><button onClick={()=>action('comment',selected)} className="rounded-full bg-[#222] px-4 text-sm font-semibold text-white">{t.submit}</button></div></div></div></div>}
 </main>
}
